### ISSUE TITLE
How do I set default values on Python class instantiation?

### ISSUE THREAD

**Issue by FJunior225** [pabigot/pyxb#105]
Hello,

I have an XSD schema below, where I have set some default boolean values and I was wondering if it is possible that PyxB would honor those default values on instantiation of Python objects or if not, how I would get that functionality. I was hoping not having to manually set up the default values.

I am under the impression that I am not using something in the generated bindings class to the fullest extent so any assistance would be appreciated.

command - `pyxbgen -u ./NewCareV2.xsd -m src/create_rna`

Thanks!

XSD Schema
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="unqualified"
     version="1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="RNA">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Entitlement" type="Entitlement">
                    <xsd:annotation>
                        <xsd:documentation>
                            <Description>Elements related to entitlement</Description>
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Entitlement">
        <xsd:sequence>
            <xsd:element name="hasPriorYearAccess" type="xsd:boolean" default="false">
                <xsd:annotation>
                    <xsd:documentation>
                        <Description>Has prior year access?</Description>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>
```

Resulting XML after instantiation of Python class -  missing `hasPriorYearAccess` boolean which I was hoping would be honored by default value
```xml
<?xml version="1.0" encoding="utf-8"?>
<RNA>
    <Entitlement/>
</RNA>
```

Sample code - hoping to avoid doing `entitlement.hasPriorYearAccess = False` because I have a large XSD with a lot of boolean values. Obviously I am just testing the default here - I removed any business logic that would set the boolean just to test default value being set.
```python
import create_rna

class RNABuilder:
  def __init__(self, current_tax_year):
        self.rna = create_rna.CTD_ANON()
       
  def with_entitled(self, load_returns):
  """testing default value"""
        entitlement = create_rna.Entitlement()
        self.rna.Entitlement = entitlement
```

**Comment by pabigot** [comment]
While defaulted attributes may be created automatically, elements inside a complex type are assumed to be absent and have to be explicitly provided.  So a default-created RNA element would have `None` as the value for the internal `Entitlement` property.

Using anonymous elements with PyXB can be inconvenient, because the names aren't obvious. [pyxb.BIND](https://pabigot.github.io/pyxb/userref_usebind.html#creating-instances-of-anonymous-types) can help.  The following would be one way to do this, though it's tedious because you have to either explicitly assign the members as shown here, or walk the content model to do it automatically.

```
import i105
import pyxb

# Create an RNA element with defaulted content for its first element
x = i105.RNA()
x.Entitlement = pyxb.BIND()
# Alternative: x = i105.RNA(pyxb.BIND())

# Nested defaulting isn't supported, so explicitly assign to default
# the content of the Entitlement element
x.Entitlement.hasPriorYearAccess = pyxb.BIND()

print x.toDOM().toprettyxml()
```
```
lilith[30]$ python t105.py 
<?xml version="1.0" ?>
<RNA>
	<Entitlement>
		<hasPriorYearAccess>false</hasPriorYearAccess>
	</Entitlement>
</RNA>
```

**Comment by FJunior225** [comment]
Is there a better way to set up my xsd schema to not have anonymous types? I am new to XSD schemas and so I am willing to change the schema if it will help in the PyxB bindings.

**Comment by pabigot** [comment]
Use a flat structure, where everything you're going to want to use directly has a name.  You should never have to search the generated bindings for `CTD_ANON`-type names; PyXB does not guarantee that the same names will be used if the bindings are re-generated.

There's a lot of ways you can approach this; I suggest searching for schema design best practices.  See, for example, [this](https://www.xml.com/pub/a/2000/11/29/schemas/part1.html#slicing) which addresses a flat schema design (I haven't actually read that, just found it with a search).

I'd also recommend making trivial simple values like `hasPriorYearAccess` an attribute on the element, rather than a sub-element.  

If you did something like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="RNA">
      <xsd:complexType>
	<xsd:sequence>
	  <xsd:element name="Entitlement" type="Entitlement"/>
	</xsd:sequence>
      </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="Entitlement">
      <xsd:sequence/>
      <xsd:attribute name="hasPriorYearAccess" type="xsd:boolean" default="false"/>
    </xsd:complexType>
</xsd:schema>
```
then you could do something like this:
```
import i105b
import pyxb

# Create an RNA element with defaulted content for its first element
x = i105b.RNA(pyxb.BIND())

# Shows attribute is defaulted
print x.Entitlement.hasPriorYearAccess

# However it doesn't get printed, because it is defaulted not explicitly set.
print x.toDOM().toprettyxml()
x.Entitlement.hasPriorYearAccess = x.Entitlement.hasPriorYearAccess

print x.toDOM().toprettyxml()
```
which would give you:
```
lilith[21]$ python t105b.py
false
<?xml version="1.0" ?>
<RNA>
	<Entitlement/>
</RNA>

<?xml version="1.0" ?>
<RNA>
	<Entitlement hasPriorYearAccess="false"/>
</RNA>
```

**Comment by FJunior225** [comment]
Ok so in terms of the default values, I will still have to explicitly set those, understandable. I will look into the XSD best practices, especially a flat structure. That will at least help with the anonymous types. 

Thank you for your assistance!

**Comment by pabigot** [comment]
No, you don't have to set those explicitly as long as whatever you're communicating with uses the same schema--the schema specifies what value should be assumed if it doesn't appear in the XML.  That's why PyXB isn't providing it in the generated XML, even though the attribute on the Python object is set correctly: it's redundant.  (And, in some cases, the simple fact that it is or is not explicitly provided is information.)

You're welcome.

**Comment by FJunior225** [comment]
Ahh ok gotcha

**Comment by FJunior225** [comment]
@pabigot just out of curiosity, you were able to instantiate RNA? It was not a CTD_ANON class?

**Comment by pabigot** [comment]
Yes; all the code examples in my responses were tested.

XML and PyXB both distinguish between elements and (complex and simple) types.   PyXB generates a class for types, and provides an instance of another class that associates that class with a namespace name in a way that allows the instance to be used to create elements.

So in your original code `create_rna.CTD_ANON()` what you're doing is creating an instance of the type internal to the RNA element, but not creating an RNA element.  If you tried to generate XML from the type alone in some situations it would fail because it wouldn't know what the element should be called.  You should always have been able to use `create_rna.RNA()` in the original version instead of `create_rna.CTD_ANON()`.

There's some information about this in the [Elements section here](https://pabigot.github.io/pyxb/arch_binding.html#id5).
