### ISSUE TITLE
datatypes.decimal call to normalize() destroys trailing zeroes

### ISSUE THREAD

**Issue by erose** [pabigot/pyxb#42]
pyxb's `decimal` datatype strips trailing zeroes in its `XsdLiteral` function.

    >>> from pyxb.binding.datatypes import decimal
    >>> from decimal import Decimal
    >>> decimal.XsdLiteral(Decimal('2.000'))
    u'2.0'

This is the result of a call to `normalize()` in the first line of `XsdLiteral` (`binding.datatypes` line 159).

    (sign, digits, exponent) = value.normalize().as_tuple()

Without normalizing, that is, with:

     (sign, digits, exponent) = value.as_tuple()

the function preserves the zeroes and appears to work fine.

The reason this is an issue for me is because I'm dealing with the Version type from [this](http://www.opentravel.org/2013A/OTA_CommonTypes.xsd) schema (ctrl+F 'name="Version" type="xs:decimal"' to find it) which is of type `decimal`. But the service I'm calling demands all 3 zeroes, and chokes if I give it `2.0` instead of `2.000`.

Is this expected behavior for pyxb? Does anything else rely on this call to `normalize()`?

**Comment by pabigot** [comment]
This is expected behavior.  From the [description of the canonical representation of an `xs:decimal` value](http://www.w3.org/TR/xmlschema-2/#decimal):

    Leading and trailing zeroes are prohibited subject to the following: there must be at least
    one digit to the right and to the left of the decimal point which may be a zero.

Generally PyXB prefers to emit XSD literals in their canonical form.  I would argue the flaw is in the service you're calling because it rejects a value that conforms to the requirements of the datatype.

I can see the value of having an explicit indication of the significant digits past the decimal point, but they are not required.  If you leave this open I'll consider adding a flag that would allow them to be retained (more likely, added or removed to pad to the number of fractionDigits), but it's probably not going to ever be fixed.  (Looking at the schema, it wouldn't help in your case because they don't specify how many digits they want in the version.  Probably shouldn't be using `decimal` for that attribute; maybe `string`.)

**Comment by pabigot** [comment]
If you need further evidence to convince the schema provider to fix the schema, see the first paragraph of the description:

    Precision is not reflected in this value space; the number 2.0 is not distinct 
    from the number 2.00.

Based on that I've changed my mind on considering an option to preserve precision.  Sorry.  They should probably use a pattern restriction on `xs:string` if they want trailing zeros.

**Comment by erose** [comment]
Great! Thanks for the detective work, perhaps I've learned to look at w3schools myself next time. The [schema](http://www.opentravel.org/2003A/OTA_CommonTypes.xsd) is from the [Open Travel Alliance](www.opentravel.org) so there's no hope of getting it changed -- instead I think I'll try to persuade the service providers to accept any number of zeroes, since it seems that they are indeed using it wrong for the schema.
