### ISSUE TITLE
ValidationConfig Usage

### ISSUE THREAD

**Issue by brianmc** [pabigot/pyxb#53]
Apologies upfront for this newbie question but I'm struggling to find any good examples of ValidationConfig.  We're currently using pyxb.RequireValidWhenParsing(False) which is simply called before CreateFromDocument(self._httpResponse).

However we know that is a legacy method and we need the finer grained control that ValidationConfig class gives.  However when we do something like below, there is no change in the parsing and I feel like I'm missing some very obvious Python convention.

pyxb.GlobalValidationConfig.invalidElementInContent = -1

**Comment by pabigot** [comment]
The only example I have to hand is [xhtml1.py](https://github.com/pabigot/pyxb/blob/next/pyxb/bundles/common/xhtml1.py).  And the [documentation](http://pyxb.sourceforge.net/api/pyxb.ValidationConfig-class.html).  From what I can see there -1 means `always` which isn't documented as an allowed selection for that option.

As I recall I created this feature solely to handle XHTML where normal usage requires preserving more information than XML schema strictly requires.  PyXB wasn't really intended for use without validating the content, so the capability of bypassing validation doesn't get a lot of attention.

**Comment by brianmc** [comment]
Thank-you Peter, really appreciate the prompt response.

**Comment by brianmc** [comment]
@pabigot Any recommendations for an alternative library which would allow deserialization with "IgnoreUnknownElements" semantics?

**Comment by pabigot** [comment]
There used to be a system called generateDS that was similar to PyXB but didn't do validation.  No idea if it's still active, nor am I familiar with any other alternatives.

**Comment by brianmc** [comment]
Thanks again for responding so quickly, I'll check out generateDS.

**Comment by brianmc** [comment]
And thanks for creating and maintaining Pyxb of course!

**Comment by brianmc** [comment]
I know you said Pyxb was intended to validate content but I just wanted to check one issue before I looked into generateDS.    When I turn off validation I'm getting StructuralBadDocumentError (see stack trace below).

The very simple sample I'm using is from http://pyxb.sourceforge.net/userref_pyxbgen.html#pyxbgen 
After I had the sample running I simply updated the XML with an additional element - https://gist.github.com/brianmc/9ab358da1a2ab95d3b15e025114af7cd

I have gists for the other files as well, the demo python script is just a few lines (https://gist.github.com/brianmc/bc16322ef884e3213cba71a18ab674f5):

````python
xml = open('po2.xml').read()
pyxb.GlobalValidationConfig._setForBinding(False)
order = po1.CreateFromDocument(xml)

print('%s is sending %s %d thing(s):' % (order.billTo.name, order.shipTo.name, len(order.items.item)))
for item in order.items.item:
    print('  Quantity %d of %s at $%s' % (item.quantity, item.productName, item.USPrice))
````python 

Traceback (most recent call last):
  File "demo1.py", line 14, in <module>
    order = po1.CreateFromDocument(xml)
  File "/Users/anetdeveloper/pyxbtest/po1.py", line 63, in CreateFromDocument
    saxer.parse(io.BytesIO(xmld))
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/Library/Python/2.7/site-packages/pyxb/binding/saxer.py", line 388, in endElementNS
    binding_object = this_state.endBindingElement()
  File "/Library/Python/2.7/site-packages/pyxb/binding/saxer.py", line 238, in endBindingElement
    _location=info.location)
  File "/Library/Python/2.7/site-packages/pyxb/binding/basis.py", line 2508, in append
    raise pyxb.StructuralBadDocumentError(container=self, content=value)
pyxb.exceptions_.StructuralBadDocumentError: <class 'po1.CTD_ANON'> cannot accept wildcard content <pyxb.utils.saxdom.Element object at 0x107316510>

**Comment by pabigot** [comment]
Yeah, "disable validation" mostly means don't check whether sequence/choice/etc. constraints are met.  In this case you've added an element `sku` that doesn't have a PyXB python binding because it isn't in the original schema.

If wildcard content were allowed in the containing element PyXB would insert a DOM-compatible object at the appropriate point without checking whether the wildcard constraints were satisfied.  Apparently it won't go so far as to allow you to insert something that isn't recognized as part of the schema.

It seems that's primarily because, if the schema doesn't allow wildcards, the Python instance attributes that would hold wildcards aren't defined.  In addition to causing exceptions when added, if you regenerate XML it wouldn't restore the elements.  A "quick fix" of bypassing the check and unconditionally storing unrecognized values as wildcards causes failures in the test suite so changing this would be a behavioral change (albeit a case could be made that it's a bug fix, if "failure to process invalid xml" were a bug).

If you have control over the schema, you could add `xs:any` to the content model to make this particular problem go away.

**Comment by brianmc** [comment]
We do have control of the schema so let me give that a try, thanks!
