### ISSUE TITLE
Output filename with pyxbgen?

### ISSUE THREAD

**Issue by nowox** [pabigot/pyxb#68]
I am trying to find a way to rename my output from pyxbgen. I currently do this: 

```
pyxbgen -m foo -u foo.xsd 2>&1 1>/dev/null | grep -Ev 'WARNING.*renamed to'
mv foo.py foo.contrib.py
```

My python module is dynamically created with my Makefile, is it thus an intermediate file. Moreover I don't want to capture the irrelevant `WARNING... Foo renamed to Foo_` warnings. 

In order to ignore my intermediate files from `git status` I've added `*.contrib.*` to my `.gitignore`. 

So I primarily want to avoid calling `mv` to rename my module, but I did not find any workaround on `pyxbgen --help`

**Comment by pabigot** [comment]
Since pyxbgen may need to generate multiple files to provide bindings for a single namespace, and may generate files for multiple namespaces in each invocation, it must use file names that can be referenced as modules from other modules generated in the same session.  If the [documented options](http://pyxb.sourceforge.net/pyxbgen_cli.html#configuring-bindings) don't cover your needs you'll have to rename them after pyxbgen writes them.
